### ISSUE TITLE
a.localeCompare is not a function

### ISSUE THREAD

**Issue by etoy22** [death-save/combat-utility-belt#663]
**Descr
TypeError: Error thrown in hooked function '' for hook 'updateToken': a.localeCompare is not a function
[Detected 1 package: combat-utility-belt]

**To Reproduce**
I am not really sure all i use of this module is the condition lab and trigger

**Screenshots**
![image](https://user-images.githubusercontent.com/20910516/154183795-c97b8607-c3ed-4bd9-9577-fa9ec44b331a.png)

**Environment Info (please complete the following information):**
 - Foundry Version: Version 9
 - Game System / Version: dnd5e 1.5.6
 - CUB Version [e.g. 1.3.0]
 - Browser: Firefox
 - Windows 10

**Comment by gitfunk** [comment]
I'm getting a tonne of these errors on v9.249. 

sidekick.js:327 Uncaught (in promise) TypeError: a.localeCompare is not a function
[Detected 2 packages: combat-utility-belt, df-chat-enhance]
    at modules/combat-utility-belt/modules/sidekick.js:327:85
    at Array.sort (<anonymous>)
    at Function.getFirstGM (modules/combat-utility-belt/modules/sidekick.js:327:68)
    at Function._onRenderChatMessage (modules/combat-utility-belt/modules/concentrator.js:41:33)
    at modules/combat-utility-belt/modules/signal.js:201:26
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at ChatMessage.getHTML (foundry.js:15218:11)
    at async ChatMessage.🎁ChatMessage.prototype.getHTML#df-chat-enhance (modules/df-chat-enhance/src/main.js:1:49352)
    at async ChatLog._ChatLog_postOne (modules/df-chat-enhance/src/main.js:1:46142)
4foundry.js:316 TypeError: a.localeCompare is not a function
[Detected 1 package: combat-utility-belt]
    at modules/combat-utility-belt/modules/sidekick.js:327:85
    at Array.sort (<anonymous>)
    at Function.getFirstGM (modules/combat-utility-belt/modules/sidekick.js:327:68)
    at Function._onUpdateActor (modules/combat-utility-belt/modules/concentrator.js:138:90)
    at modules/combat-utility-belt/modules/signal.js:113:26
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10273:13)
    at foundry.js:10212:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10212:33)
    at o.<anonymous> (foundry.js:9845:28)
    at o.T.emit (socket.io.min.js:6:6439)
    at o.value (socket.io.min.js:6:33081)
    at o.value (socket.io.min.js:6:32785)
    at o.value (socket.io.min.js:6:32439)
    at s.T.emit (socket.io.min.js:6:6439)
    at s.value (socket.io.min.js:6:38463)
    at a.T.emit (socket.io.min.js:6:6439)
    at a.value (socket.io.min.js:6:27315)
    at s.value (socket.io.min.js:6:38414)
    at a.T.emit (socket.io.min.js:6:6439)
    at a.value (socket.io.min.js:6:21894)
    at o.T.emit (socket.io.min.js:6:6439)
    at o.value (socket.io.min.js:6:9311)
    at o.value (socket.io.min.js:6:9233)
    at WebSocket.ws.onmessage (socket.io.min.js:6:16388)
onError @ foundry.js:316
blue_14.jpg:1          Failed to load resource: net::ERR_FAILED
sidekick.js:327 Uncaught (in promise) TypeError: a.localeCompare is not a function
[Detected 2 packages: combat-utility-belt, df-chat-enhance]
    at modules/combat-utility-belt/modules/sidekick.js:327:85
    at Array.sort (<anonymous>)
    at Function.getFirstGM (modules/combat-utility-belt/modules/sidekick.js:327:68)
    at Function._onRenderChatMessage (modules/combat-utility-belt/modules/concentrator.js:41:33)
    at modules/combat-utility-belt/modules/signal.js:201:26
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at ChatMessage.getHTML (foundry.js:15218:11)
    at async ChatMessage.🎁ChatMessage.prototype.getHTML#df-chat-enhance (modules/df-chat-enhance/src/main.js:1:49352)
    at async ChatLog._ChatLog_postOne (modules/df-chat-enhance/src/main.js:1:46142)
18foundry.js:316 TypeError: a.localeCompare is not a function
[Detected 1 package: combat-utility-belt]
    at modules/combat-utility-belt/modules/sidekick.js:327:85
    at Array.sort (<anonymous>)
    at Function.getFirstGM (modules/combat-utility-belt/modules/sidekick.js:327:68)
    at Function._onUpdateActor (modules/combat-utility-belt/modules/concentrator.js:138:90)
    at modules/combat-utility-belt/modules/signal.js:113:26
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10273:13)
    at foundry.js:10212:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10212:33)
    at o.<anonymous> (foundry.js:9845:28)
    at o.T.emit (socket.io.min.js:6:6439)
    at o.value (socket.io.min.js:6:33081)
    at o.value (socket.io.min.js:6:32785)
    at o.value (socket.io.min.js:6:32439)
    at s.T.emit (socket.io.min.js:6:6439)
    at s.value (socket.io.min.js:6:38463)
    at a.T.emit (socket.io.min.js:6:6439)
    at a.value (socket.io.min.js:6:27315)
    at s.value (socket.io.min.js:6:38414)
    at a.T.emit (socket.io.min.js:6:6439)
    at a.value (socket.io.min.js:6:21894)
    at o.T.emit (socket.io.min.js:6:6439)
    at o.value (socket.io.min.js:6:9311)
    at o.value (socket.io.min.js:6:9233)
    at WebSocket.ws.onmessage (socket.io.min.js:6:16388)
onError @ foundry.js:316
foundry.js:316 TypeError: a.localeCompare is not a function
[Detected 1 package: combat-utility-belt]
    at sidekick.js:327:85
    at Array.sort (<anonymous>)
    at Function.getFirstGM (sidekick.js:327:68)
    at Function._onUpdateActor (concentrator.js:138:90)
    at signal.js:113:26
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10273:13)
    at foundry.js:10212:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10212:33)
    at o.<anonymous> (foundry.js:9845:28)
    at o.T.emit (index.js:143:20)
    at o.value (socket.js:276:20)
    at o.value (socket.js:263:18)
    at o.value (socket.js:231:22)
    at s.T.emit (index.js:143:20)
    at s.value (manager.js:200:14)
    at a.T.emit (index.js:143:20)
    at a.value (index.js:105:51)
    at s.value (manager.js:192:22)
    at a.T.emit (index.js:143:20)
    at a.value (socket.js:323:26)
    at o.T.emit (index.js:143:20)
    at o.value (transport.js:99:14)
    at o.value (transport.js:92:14)
    at WebSocket.ws.onmessage (websocket.js:76:40)

**Comment by eclarke12** [comment]
@gitfunk it will be fixed in v1.8.3, coming out today or tomorrow.
